apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    name: letsencrypt-prod
spec:
  acme:
    email: muzz@acemuzzy.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          #class: nginx
          name: letsencrpyt-ingress
          # podTemplate:
          #   spec:
          #     nodeSelector:
          #       "kubernetes.io/os": linux         